baseURL: "https://joaovitormonica87-cmyk.github.io/jv-engineering-website/"
canonifyURLs: true
relativeURLs: false

title: "JV Engineering"
summaryLength: 20
languageCode: "pt-br"

# services:
#   googleAnalytics:
#     id: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true